In [6]:
'''
@Author: Subhadeep Bhattacharjee
@Date: 2021:12:04 15:10
@Title: Create a 3*3 matrix with values from 2-10

'''

'\n@Author: Subhadeep Bhattacharjee\n@Date: 2021:12:04 15:10\n@Title: Convert a list of numerical values into one-D array\n\n'

In [8]:
import numpy as np

matrix = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
