In [ ]:
'''
@Author: Subhadeep Bhattacharjee
@Date: 2021:12:05 23:10
@Title: Add an extra column to an existing array

'''

In [3]:
import numpy as np

arr = np.array([10,20,30,40]).reshape(2,2)
print(arr)
arr2 = np.array([[90],[100]])
print("After adding column: \n", np.append(arr,arr2,1))

[[10 20]
 [30 40]]
After adding column: 
 [[ 10  20  90]
 [ 30  40 100]]
