In [ ]:
'''
@Author: Subhadeep Bhattacharjee
@Date: 2021:12:05 14:25
@Title: Change data type of array

'''

In [2]:
import numpy as np

arr = np.array([[2,4,6],[7,8,9]])
print("The int32 array: \n",arr)
arr = np.array(arr, dtype= float)
print("After changing to float: \n",arr)

The int32 array: 
 [[2 4 6]
 [7 8 9]]
After changing to float: 
 [[2. 4. 6.]
 [7. 8. 9.]]
