In [ ]:
'''
@Author: Subhadeep Bhattacharjee
@Date: 2021:12:04 18:30
@Title: Add an extra border of zeros to an existing matrix of ones

'''

In [1]:
import numpy as np

array = np.ones((3,3))
print(array)
print("After adding border--")
array = np.pad(array, pad_width= 1 ,mode= 'constant', constant_values = 0)
print(array)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
After adding border--
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
