In [13]:
'''
@Author: Subhadeep Bhattacharjee
@Date: 2021:12:04 16:30
@Title: Create a 2D array with 1 and then replace all the elements except the border element as 0

'''

'\n@Author: Subhadeep Bhattacharjee\n@Date: 2021:12:04 16:30\n@Title: Create a 2D array with 1 and then replace all the elements except the border element as 0\n\n'

In [14]:
import numpy as np

array = np.ones((5,5))
print(array)
print("After adding zeros to the middle--")
array[1:4,1:4] = 0   # this means that the data is assigned 0zeros at those positions. 
print(array)         #1:4, means all rows from 1 to 4(excluding 4) 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
After adding zeros to the middle--
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
