In [1]:
'''
@Author: Subhadeep Bhattacharjee
@Date: 2021:12:05 15:00
@Title: Ones as diagonal element 

'''

'\n@Author: Subhadeep Bhattacharjee\n@Date: 2021:12:05 15:00\n@Title: Ones as diagonal element \n\n'

In [2]:
import numpy as np


x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
