In [ ]:
'''
@Author: Subhadeep Bhattacharjee
@Date: 2021:12:05 16:10
@Title: To create an array of shape (3,4) and multiply elements by 3

'''

In [1]:
import numpy as np

arr = np.arange(12).reshape(3,4)    #use reshape with arrange to create such arrays
print(arr)
arr = arr * 3                      #consatnt multiplication
print("New array elements:")
print(arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
