In [ ]:
'''
@Author: Subhadeep Bhattacharjee
@Date: 2021:12:05 15:20
@Title: Lower triangular matrix 

'''

In [5]:
import numpy as np

arr = np.ones((4,3))
print(arr)
print(np.tril(arr,k=-1))          #The other variation of this is the triu command. for upper traingluar matrix


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
